FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir confluent-kafka

COPY data/ ./data/
COPY data_ingestion/ ./data_ingestion/

# QUAN TRỌNG: Chuyển WORKDIR vào data_ingestion
# để Python tìm thấy kafka_producer.py khi import
WORKDIR /app/data_ingestion

CMD ["python", "-u", "bot_simulation.py"]
